compatibility with nested_fit output files
handley-lab/anesthetic pull request #327
Opened 2023-08-07 14:05 UTC by martinit18

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

Fixes # (issue)

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] My code is PEP8 compliant (`flake8 anesthetic tests`)
- [ ] My code contains compliant docstrings (`pydocstyle --convention=numpy anesthetic`)
- [ ] New and existing unit tests pass locally with my changes (`python -m pytest`)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have appropriately incremented the [semantic version number](https://semver.org/) in both README.rst and anesthetic/_version.py

2023-08-07 14:06 UTC, martinit18 commented
Please find a more complete pool here

2023-08-07 20:56 UTC, martinit18 commented
Sorry for this back-forward but it is my first real pull request

2023-08-07 21:59 UTC, williamjameshandley requested changes
Looking good @martinit18, just one minor code clean-up and you're ready to merge -- accept the collaborator request and you'll then be able to squash and merge (and not need approval with new pushes).

In addition, you should increase the minor version number so that the version reads `2.2.0`, since we're adding functionality (see [semantic versioning](https://semver.org/))

2023-08-07 21:59 UTC, williamjameshandley commented on anesthetic/read/nestedfit.py
> +    dead_file = root + 'nf_output_points.txt'
This is best achieved with:
```python
dead_file = os.path.join(root, 'nf_output_points.txt')
```
and the same for `data_birth` and `root_getdist`

2023-08-08 03:52 UTC, lukashergt commented
Nice, I've incremented the version to 2.2.0 to reflect that we now have nested_fit compatibility :)

2023-08-11 21:52 UTC, martinit18 commented
I changed the code accordingly to your suggestions.

2023-08-12 11:00 UTC, williamjameshandley approved these changes
Many thanks @martinit18. Please press 'squash and merge'.

2023-08-12 13:01 UTC, merged